---

- op: add
  path: /spec/versions/0/schema/openAPIV3Schema/properties/status/properties/clusterState/enum
  value: ["Initializing", "Normal", "ScalingOut", "ScalingIn", "IncreasingReplicas", "DecreasingReplicas", "UpgradingVersion"]
